### ISSUE TITLE
【bug】win11下拖拽窗口会自己变大

### ISSUE THREAD

**Issue by djkloop** [TyphonEX/electron-drag-window#1]
win11下拖拽窗口会自己变大

```json
{
  "dependencies": {
    "@vueuse/core": "^10.2.1",
    "ant-design-vue": "4.x",
    "dexie": "^3.2.4",
    "electron-drag-window": "^0.0.3",
    "pinia": "^2.1.6",
    "vue": "^3.3.4",
    "vue-router": "^4.2.4"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^0.39.8",
    "@iconify/json": "^2.2.95",
    "@types/node": "^20.4.5",
    "@unocss/preset-icons": "^0.54.0",
    "@unocss/preset-uno": "^0.54.0",
    "@unocss/transformer-directives": "^0.54.0",
    "@unocss/transformer-variant-group": "^0.54.0",
    "@vitejs/plugin-vue": "^4.1.0",
    "electron": "^24.4.0",
    "electron-builder": "^23.6.0",
    "eslint": "^8.46.0",
    "sass": "^1.64.1",
    "typescript": "^5.0.2",
    "unocss": "^0.54.0",
    "unplugin-auto-import": "^0.16.6",
    "unplugin-vue-components": "^0.25.1",
    "vite": "^4.3.2",
    "vite-plugin-electron": "^0.11.2",
    "vite-plugin-electron-renderer": "^0.14.5",
    "vite-plugin-vue-devtools": "1.0.0-beta.5",
    "vue-tsc": "^1.4.2"
  }
```

用的脚手架： 
```sh
# https://electron-vite.github.io/
# https://github.com/electron-vite/electron-vite-vue
```

#### 使用方式
![image](https://github.com/TyphonEX/electron-drag-window/assets/21050914/f902e910-1c2a-4755-9693-7c9bde1bd1c7)

https://github.com/TyphonEX/electron-drag-window/assets/21050914/69ccba8b-765b-49d3-930a-2ed30126f19c

**Comment by djkloop** [comment]
推测应该是跟windows上的缩放比有关。
https://github.com/SingleMai/electron-dpi-drag/tree/master

**Comment by djkloop** [comment]
#### 看上去是个老bug
https://github.com/electron/electron/issues/10862

**Comment by TyphonEX** [comment]
@djkloop 谢谢你的反馈，由于最近忙着找工作没有看issues，我会重现，并且尝试修复，尽快，请稍微等待一下

**Comment by TyphonEX** [comment]
@djkloop 

> #### 看来是个老bug
> [电子/电子#10862](https://github.com/electron/electron/issues/10862)

~新版本的Electron  会修复该问题~
但是旧 Eelectron 版本中依旧存在。我已经试出一个可行解决方案，接下来会发布新版本解决这个问题

_________________

我的错，我把vscode的修复当成Electron的，但是并不影响我的修复，当前版本已经解决了该问题

**Comment by TyphonEX** [comment]
@djkloop 在新的 v0.1.0 版本中已经修复该问题，请更新一下 electron-drag-window 版本，感谢您的支持，如果还有问题的话，可以继续反馈
