### ISSUE TITLE
可不可以支持定义哪部分可以拖动，不只是忽略

### ISSUE THREAD

**Issue by buhuia** [TyphonEX/electron-drag-window#4]
大佬你好～
我这边的使用情况是我只想要一个button支持拖拽，hover提示相关信息，官网的drag属性会导致hover被覆盖掉，没办法使用。。
这个包现在是挂全局，然后忽略具体的类。也很怪。不知道可不可支持一下指定类或者id支持拖拽呢。感谢🙏

**Comment by TyphonEX** [comment]
> 大佬你好～ 我这边的使用情况是我只想要一个button支持拖拽，hover提示相关信息，官网的drag属性会导致hover被覆盖掉，没办法使用。。 这个包现在是挂全局，然后忽略具体的类。也很怪。不知道可不可支持一下指定类或者id支持拖拽呢。感谢🙏

你好，感谢你的使用，我现在才看你的请求。首先我先解释一下为什么是全局监听，是为了最大化减少使用过程，定义大量的可拖拽的元素。采用忽略是为了同样是为了以块的模式切换，最简化实现常见的某个局部使用。

你这种使用场景确实是需要考虑的，我会尽快添加支持。请稍等一下

**Comment by TyphonEX** [comment]
> > 大佬你好～ 我这边的使用情况是我只想要一个button支持拖拽，hover提示相关信息，官网的drag属性会导致hover被覆盖掉，没办法使用。。 这个包现在是挂全局，然后忽略具体的类。也很怪。不知道可不可支持一下指定类或者id支持拖拽呢。感谢🙏
> 
> 你好，感谢你的使用，我现在才看你的请求。首先我先解释一下为什么是全局监听，是为了最大化减少使用过程，定义大量的可拖拽的元素。采用忽略是为了同样是为了以块的模式切换，最简化实现常见的某个局部使用。
> 
> 你这种使用场景确实是需要考虑的，我会尽快添加支持。请稍等一下

@buhuia 你好，我已发布v1.0.3版本，对你的这种情况进行了兼容处理。详情可看最新版本的 readme。现在已增加了拖拽模式可选项

**Comment by buhuia** [comment]
感谢支持~
