### ISSUE TITLE
win10下 不显示悬浮logo

### ISSUE THREAD

**Issue by hanfeicode** [TyphonEX/electron-drag-window#5]
win10下  安装了你那个示例TyphonNote  可以使用 但是不显示悬浮logo
bro 有无详细的示例代码，谢谢。

**Comment by TyphonEX** [comment]
@hanfeicode 

如果是问 TyphonNote 的话，是需要开启悬浮模式

如果是问实现的话，这个根据自身代码和项目去实现即可，简单的就是将
1. 将窗口缩放至悬浮球大小
2. 将悬浮球元素设为可拖拽元素
3. 在拖拽元素上实现自身业务逻辑
