### ISSUE TITLE
子元素的点击事件会被触发，怎么阻止？

### ISSUE THREAD

**Issue by Jony1943** [TyphonEX/electron-drag-window#7]
我想整个父元素包括子元素都可以拖动，但是拖动结束会触发子元素的点击事件，怎么阻止呢？

**Comment by TyphonEX** [comment]
click 事件 和 mousedown/mouseup 事件本身就是先后触发，甚至可以说是一体的，正常的触发拖拽是一定会触发click。
并且 mousedown 是先与 click 触发，因此并不能有效的判断是否要阻止/触发点击事件。

这种拖拽与点击元素并存的，通常也会出现在 表格内拖拽排序。

可以参考市面上常见的解决方案处理，我这里列举两个
1. 增加拖拽元素，让用户通过拖拽元素拖拽
2. 在拥有点击事件元素上增加事件拦截，阻止 mousedown 事件的冒泡

**Comment by TyphonEX** [comment]
或者通过技术方案，通过 mousedown 和 mouseup 自实现点击事件，当用户mousedown 和 mouseup 的间隔小于多少秒时视为触发单击事件
